language: 
  - python

python:
  - "2.7.6"

before_script:
  - sudo pip install -r requirements.txt
  - sudo apt-get install pylint

script: 
  - pylint stock_alerter/ -f parseable > analysis.txt || true
  - nose2 --junit-xml --with-coverage 

# Requires TESTSPACE_TOKEN environment variable.   
after_script:
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin
  - testspace @.testspace.txt $TESTSPACE_TOKEN/${TRAVIS_REPO_SLUG/\//:}/${TRAVIS_BRANCH}#travis.Build.${TRAVIS_BUILD_NUMBER}
 