language: 
  - python

python:
  - "2.7.6"

before_script:
  - sudo pip install -r requirements.txt
  - sudo apt-get install pylint

script: 
  - pylint stock_alerter/ -f parseable > analysis.txt || true
  - nose2 -X -C --coverage-report xml

after_script:
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin
  - testspace analysis.txt{issues} [Tests]nose2.xml{stock_alerter} coverage.xml $TESTSPACE_TOKEN/${TRAVIS_BRANCH}#travis.Build.${TRAVIS_BUILD_NUMBER}
  
