language: python
python:
  - "2.7.6"
before_script:
  # Install Testspace Runner
  - ./testspace_install.sh
  - sudo pip install -r requirements.txt
script: 
  - nose2 -X -C --coverage-report xml
  
  # Publish Test Results along with Coverage
  - export PATH="${HOME}/testspace:${PATH}"
  # Testspace credentials: "credentials@myorg.testspace.com/myproject/myspace"
  - testspace config url ${TESTSPACE_USER_TOKEN}:@${TESTSPACE_URL}
  - testspace publish [Tests]nose2.xml coverage.xml